services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  auth-app:
    build: .
    ports:
      - "8015:8015"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authentication
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres