spring:
  application:
    name: authentication

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

  twilio:
    account:
      sid: ${TWILIO_ACCOUNT_SID}
    auth:
      token: ${TWILIO_AUTH_TOKEN}
    phone:
      number: ${TWILIO_PHONE_NUMBER}

server:
  port: 8015
  servlet:
    context-path: /authentication/v1.0 # TODO: versioning must be at the controller level not environment level.